/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:9365d195-6432-4d08-9544-35ee50dbb044",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_PhrjN2VuW",
    "aws_user_pools_web_client_id": "54q04a0nu3k7giiguki8s10dea",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://ihrdl7jh5rgojd7mqcxhmoi7ha.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "da2-u4bkakdmbjf77cbkgepiow2klu",
    "aws_user_files_s3_bucket": "ubikfarmaapp4f7a173bc50c465fb2307e4f7ad67cdebe8ba-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
